export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const GET_ERROR = "GET_ERROR";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const GET_ONE_BRAND = "GET_ONE_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";
export const UPDATE_BRAND = "UPDATE_BRAND";

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";
export const GET_ALL_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";
export const DELETE_SUB_CATEGORY = "DELETE_SUB_CATEGORY";
export const UPDATE_SUB_CATEGORY = "UPDATE_SUB_CATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_BY_CATEGORY = "GET_ALL_PRODUCT_BY_CATEGORY";
export const GET_ALL_PRODUCT_BY_BRAND = "GET_ALL_PRODUCT_BY_BRAND";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const CREATE_USER = "CREATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const Forget_PASSWORD = "Forget_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD";

export const CREATE_RATE = "CREATE_RATE";
export const GET_ALL_RATE = "GET_ALL_RATE";
export const DELETE_RATE = "DELETE_RATE";
export const UPDATE_RATE = "UPDATE_RATE";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const GET_ALL_WISHLIST = "GET_ALL_WISHLIST";

export const ADD_COUPON = "ADD_COUPON";
export const GET_ALL_COUPON = "GET_ALL_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";
export const GET_ONE_COUPON = "GET_ONE_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";

export const CREATE_USER_ADDRESS = "CREATE_USER_ADDRESS";
export const GET_ALL_USER_ADDRESS = "GET_ALL_USER_ADDRESS";
export const DELETE_USER_ADDRESS = "DELETE_USER_ADDRESS";
export const UPDATE_USER_ADDRESS = "UPDATE_USER_ADDRESS";
export const GET_ONE_USER_ADDRESS = "GET_ONE_USER_ADDRESS";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const ALL_USER_CART = "ALL_USER_CART";
export const DELETE_ALL_CART = "DELETE_ALL_CART";
export const DELETE_ONE_CART = "DELETE_ONE_CART";
export const UPDATE_COUNT_CART = "UPDATE_COUNT_CART";
export const APPLY_COUPON_CART = "APPLY_COUPON_CART";
