export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_ERROR = "GET_ERROR";

export const GET_ALL_BRAND = "GET_ALL_BRAND";
export const GET_ONE_BRAND = "GET_ONE_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const CREATE_USER = "CREATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const Forget_PASSWORD = "Forget_PASSWORD";
export const VERIFY_PASSWORD = "VERIFY_PASSWORD";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const CREATE_RATE = "CREATE_RATE";
export const GET_ALL_RATE = "GET_ALL_RATE";
export const DELETE_RATE = "DELETE_RATE";
export const UPDATE_RATE = "UPDATE_RATE";


